version: '3.9'

services:
  # PostgreSQL database service
  db:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - transcendance_net
    volumes:
      - /tmp/db_data:/var/lib/postgresql/data # Volume nommé

  # Adminer for DB management
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - transcendance_net
    depends_on:
      - db

  # Service frontend pour un serveur web simple avec HTML, CSS, JS
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html # Volume monté, A supprimer apres la phase de dev
    ports:
      - '80:80'
    networks:
      - transcendance_net

  # # Backend service
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - '5000:5000'
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_HOST: db
  #   networks:
  #     - transcendance_net
  #   depends_on:
  #     - db

# Volumes pour stocker les données de PostgreSQL
volumes:
  db_data:

# Réseau pour la communication entre services
networks:
  transcendance_net:
    driver: bridge
