# Stage 1: Build the Vue.js application
FROM node:18-alpine as build-stage

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install pinia
RUN npm install mitt

# Copy project files
COPY . .

# Build the app
RUN npm run build
